### ISSUE TITLE
Consider listing the responses to `Invoicing.Order.Deleted` in the events overview

### ISSUE THREAD

**Issue by ivan-wolf** [Garaio-REM/remcloud-message-bus-api#5]
The following two events seem to have been introduced with https://github.com/Garaio-REM/remcloud-message-bus-api/commit/38f9309e873e30d45e4b369561d47b5e5ae76311#diff-35b7cb820bfa30614ee42bf081afa03676c9ec583eafbbd19fbd3064d0e7f054R191 as response to `Invoicing.Order.Deleted` messages:

- [Invoicing.Order.DeletedAccepted](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/invoicing_context.md#invoicingorderdeletedaccepted)
- [Invoicing.Order.DeletedRejected](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/invoicing_context.md#invoicingorderdeletedrejected)

These events should probably be listed [here](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/invoicing_context.md#events).

**Comment by gernotkogler** [comment]
You're right, they were introduced with that commit. We're currently make a transition to two message types: events and commands. Event Messages reflect an event that occurred in GARAIO REM, eg [[Letting.Tenancy.Created](https://github.com/Garaio-REM/remcloud-message-bus-api/issues/5#lettingtenancycreated)](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/letting_context.md#lettingtenancycreated)

Command messages, on the other hand, send a command to GARAIO REM expecting something to happen there. Example: [Invoicing.Invoice.Created](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/invoicing_context.md#invoicinginvoicecreated). Command messages will always reply with an accepted / rejected message. And they will reflect the command in their name, `Invoicing.Invoice.Created` will be renamed to  `Invoicing.Invoice.Create` in the future. The accept / reject messages will be renamed to `Invoicing.Invoice.CreateAccepted` / `Invoicing.Invoice.CreateRejected`. Since this is a generic pattern we will not list the accepted / rejected messages in the messages overview. Please find further information about this new pattern [here](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/result_messages.md)

Of course, we will inform you as soon as we are ready with the transition and we will still support (but deprecate) the old message names until all of our partners and customers are ready to make the switch.

**Comment by ivan-wolf** [comment]
Thanks, @gernotkogler, for the feedback and the explanations!

It's a bit off-topic, but since we're already discussing this: 
I think the separation between commands and events is helpful. Did you consider taking this a step further and offer the commands through GraphQL? It would make things much simpler when it comes to integrating with Garaio REM, since there'd be synchronous feedback (no need for correlate sent commands with received events only to know if the command was accepted or rejected).

**Comment by gernotkogler** [comment]
Hi @ivan-wolf Interesting that you mention GraphQL mutations. We had and will have several internal discussions on this topic. While synchronous calls make some things simpler, they make other things more difficult (eg handling unavailable endpoints). The command message pattern is actually a well understood [Enterprise Integration Pattern](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CommandMessage.html)
